#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Unit tests for <if_group_name>
Covers: UF-XX (<goal>), UF-YY (<goal>)

Generated by: uf-implementor
Source: uf.md acceptance criteria
"""

import pytest
import numpy as np
from src.uf.<module_name> import uf_XX_<snake_name>, uf_YY_<snake_name>


# ══════════════════════════════════════════════════════════
# Fixtures
# ══════════════════════════════════════════════════════════

@pytest.fixture
def nominal_input():
    """Standard valid input for UF-XX."""
    return np.random.rand(<dim>,).astype(np.float32)


@pytest.fixture
def nominal_input_yy():
    """Standard valid input for UF-YY."""
    return np.random.rand(<dim2>,).astype(np.float32)


# ══════════════════════════════════════════════════════════
# UF-XX Tests
# ══════════════════════════════════════════════════════════

class TestUfXX:
    """Tests for uf_XX_<snake_name>"""

    def test_nominal_output_shape(self, nominal_input):
        """Happy path: output shape matches expected."""
        result = uf_XX_<snake_name>(nominal_input)
        assert result.shape == (<out_dim>,), f"Expected shape (<out_dim>,), got {result.shape}"

    def test_nominal_output_dtype(self, nominal_input):
        """Happy path: output dtype is float32."""
        result = uf_XX_<snake_name>(nominal_input)
        assert result.dtype == np.float32

    def test_acceptance_criteria(self, nominal_input):
        """Given <situation from UF Block>,
        When uf_XX_<snake_name>() runs,
        Then <metric> >= <threshold> (acceptance criterion)."""
        result = uf_XX_<snake_name>(nominal_input)
        metric = <compute_metric_function>(result)
        assert metric >= <threshold>, (
            f"Acceptance criterion failed: expected {<metric_name>} >= {<threshold>}, got {metric:.4f}"
        )

    def test_rejects_nan_input(self):
        """Edge case: NaN input raises ValueError."""
        bad_input = np.full((<dim>,), np.nan, dtype=np.float32)
        with pytest.raises(ValueError, match="NaN"):
            uf_XX_<snake_name>(bad_input)

    def test_rejects_wrong_type(self):
        """Edge case: non-ndarray input raises TypeError."""
        with pytest.raises(TypeError):
            uf_XX_<snake_name>([1.0, 2.0, 3.0])  # list instead of ndarray

    # Add more edge cases from the UF Block's "Edge Cases" field:
    # def test_<edge_case_name>(self):
    #     ...


# ══════════════════════════════════════════════════════════
# UF-YY Tests
# ══════════════════════════════════════════════════════════

class TestUfYY:
    """Tests for uf_YY_<snake_name>"""

    def test_nominal_output_shape(self, nominal_input_yy):
        result = uf_YY_<snake_name>(nominal_input_yy)
        assert result.shape == (<out_dim2>,)

    def test_acceptance_criteria(self, nominal_input_yy):
        """Given <situation>, When uf_YY runs, Then <metric> >= <threshold>."""
        result = uf_YY_<snake_name>(nominal_input_yy)
        metric = <compute_metric>(result)
        assert metric >= <threshold2>, f"Expected >= {<threshold2>}, got {metric:.4f}"

    def test_rejects_nan_input(self):
        bad = np.full((<dim2>,), np.nan, dtype=np.float32)
        with pytest.raises(ValueError):
            uf_YY_<snake_name>(bad)


# ══════════════════════════════════════════════════════════
# I/O Chain Tests (UF-XX → UF-YY)
# ══════════════════════════════════════════════════════════

class TestIOChain:
    """Validate that the output of UF-XX feeds into UF-YY without type mismatch."""

    def test_uf_xx_to_yy_chain(self, nominal_input):
        """End-to-end: UF-XX output can be passed directly to UF-YY."""
        intermediate = uf_XX_<snake_name>(nominal_input)
        result = uf_YY_<snake_name>(intermediate)
        assert result is not None
        assert not np.any(np.isnan(result))
